---
title: Nirav's Blog
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/project/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
url: https://nirav.com.np
description: ''
theme_settings:
  title: Nirav's Blog
  favicon: assets/favicon.ico
  gravatar: 
  header_text: 
  header_feature_image: 
  footer_text: '&copy; Nirav Nikhil. <a href="/about/">About me.</a>

'
  rss: true
  email_address: mail@nirav.com.np
  behance: 
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  gitlab: 
  github: niravcodes
  google_plus: 
  instagram: 
  keybase: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: https://stackexchange.com/users/3242498/nirav
  steam: 
  tumblr: 
  twitter: 
  vimeo: 
  wordpress: 
  youtube: 
  share_buttons:
    facebook: true
    twitter: true
    google_plus: false
    tumblr: 
    pinterest: 
    pocket: 
    reddit: true
    linkedin: 
    wordpress: 
    email: true
  google_analytics: UA-131574406-1
  disqus_shortname: nirav-2
  katex: false
  special_page:
    search:
      icon: search
      enabled: true
    tags:
      icon: tags
      enabled: true
  str_follow_on: Follow on
  str_rss_follow: Follow RSS feed
  str_share_on: Share on
  str_add_to: Add to
  str_email: Email
  str_tweet: Tweet
  str_pin_it: Pin it
  str_next_post: Next post
  str_previous_post: Previous post
  str_next_page: Next
  str_previous_page: Prev
  str_javascript_required_disqus: Please enable JavaScript to view comments.
  google_fonts: Poiret+One|EB+Garamond:400,400i,700,700i
  google_fonts_nepali: Poiret+One|EB+Garamond:400,400i,700,700i|Cambay&display=swap&subset=devanagari
  post_navigation: false
paginate: 10
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- type-on-strap.gemspec
- "*.gem"
- LICENSE
- README.md
- screenshot.png
- package.json
- node_modules
- gulpfile.js
- ".idea/*"
