# SITE CONFIGURATION
baseurl: ""
url: "https://nirav.com.np"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Nirav's blog
#  avatar: assets/img/owl.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Blog of an engineering student who doesn't do much" # used by search engines

  # Header and footer text
  header_text: >
     <p>Hey.</p><p>I'm Nirav. I study computer engineering in Nepal.</p>
     <p>I dabble with electronics, programming, art, design, music and everything in between. You could call me a jack of all trades. </p>
  header_text_feature_image: "assets/img/astrology-astronomy-background-image-956981 (1).jpg"
  footer_text: >
   &copy; Nirav Nikhil. <a href="/about/">About/Contact me.</a> 

  # Icons
  rss: true
  email_address: niravnikhil@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "mynameistakenisalsotaken"
  google_plus:
  instagram: "kawaii.hermit"
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: UA-131574406-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup
  portfolio: false
  search: true
  tags: true
  
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lora:400,400i|Work+Sans:800"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 6
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

#Prose configuration
prose:
  rooturl: "_posts"
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  siteurl: "http://nirav.com.np"
  media: "assets/img/images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
          - name: "Random"
            value: "random"
          - name: "Linux"
            value: "linux"
          - name: "Web design"
            value: "web-design"
          - name: "Article"
            value: "article"
          - name: "Review"
            value: "review"
          - name: "Code"
            value: "code"
          - name: "Thoughts"
            value: "thoughts"
          - name: "Python"
            value: "python"
          - name: "Electronics"
            value: "electronics"
          - name: "Project"
            value: "Project"
          - name: "Tinkering"
            value: "tinkering"
          - name: "Experiment"
            value: "experiment"
      - name: "feature-img"
        field:
          element: "text"
          placeholder: "/assets/img/images/image.jpg"
          label: "Link for the featured image of this post"
          value: ""
      - name: "thumbnail"
        field:
          element: "text"
          placeholder: "/assets/img/thumbnails/thumb.jpg"
          label: "Thumbnail for the featured image"
          value: ""


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "CNAME"]
