---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _portfolio
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: pages
  label: Pages
  create: documents
  match: "**/*"
upload_dir: assets/img
public_path: https://nirav.com.np/assets/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
