---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Project Title
  description: The name or title of project
  config:
    required: true
- type: tag_list
  name: tags
  label: Tags
- type: file
  name: img
  label: Project Image
- type: file
  label: Feature Image
  name: feature-img
- type: text
  label: Layout
  name: layout
  description: Always post. Don't bother changing
  config:
    required: true
  default: post
pages:
- _portfolio/self-balancing-robot-mimo.md
- _portfolio/humbird.md
- _portfolio/huffman-compression.md
- _portfolio/dot-matrix-display-system-and-animation-software.md
